# A example of the configuration file nested connectors
- name: "study1"
  metadata:
    trial: "demo_trial"
    root_path: !expr system.file(package = "connector")
  datasources:
    - name: "adam_fs"
      backend:
          type: "connector_fs"
          path: "{metadata.root_path}/{metadata.trial}/adam"

- name: "study2"
  metadata:
    trial: "demo_trial"
    root_path: !expr system.file(package = "connector")
  datasources:
    - name: "adam_fs"
      backend:
          type: "connector_fs"
          path: "{metadata.root_path}/{metadata.trial}/adam"
