# A example of the configuration file for FS and Database
metadata:
  trial: "demo_trial"
  root_path: !expr system.file(package = "connector")
  extra_class: "test2"

datasources:
  - name: "adam"
    backend:
        type: "connector_fs"
        path: "{metadata.root_path}/{metadata.trial}/adam"
        extra_class: "{metadata.extra_class}"
  - name: "sdtm"
    backend:
        type: "connector_dbi"
        drv: "RSQLite::SQLite()"
        dbname: ":memory:"
