# A example of the configuration file for FS and NovoNordisk
metadata:
  trial: "0003"
  project: "nn1234"
  instance: "current"
  root_path: "/home/novonordisk"
datasources:
  - name: "data_fs"
    backend:
        type: "fs"
        path: "{root_path}/{project}/{trial}/{instance}/stats/data/{name}"
  - name: "general_fs"
    backend:
        type: "fs"
        path: "{root_path}/{project}/{trial}/{instance}/stats/{name}"
#Idea for specific backend configuration
# specs:
#   datasources:
#     # Specify backend from other namespace than connector
#     - name: "roche_fs"
#       backend:
#           type: "roche::fs"
#           some_other_arg_than_path: "something different"
#     # Specify that we should use the roche method
#     - name: "fs_rochemethod"
#       backend:
#           type: "fs"
#           extraclass: "roche"
#           path: "something different"
