# A example of the configuration file for FS and Database
metadata:
  trial: "demo_trial"
  root_path: !expr list.files(tempdir(), pattern = "connector", full.names = TRUE)
  extra_class: "{env.hello}"
  R: "{env.R_HOME}"

env:
  hello: "world"
  RSQLite_db: ":memory:"
  system_path: "path: {env.PATH}"

datasources:
  - name: "adam"
    backend:
        type: "connector_fs"
        path: "{metadata.root_path}/{metadata.trial}/adam"
        extra_class: "{metadata.extra_class}"
  - name: "sdtm"
    backend:
        type: "connector_dbi"
        drv: "RSQLite::SQLite()"
        dbname: "{env.RSQLite_db}"
